services:
  examplesite-app:
    image: examplesite-app
    container_name: examplesite-app
    build:
      context: ./docker
    volumes:
      - ./src:/var/www/html
      - ./php-config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - examplesite-db
      - examplesite-redis
    environment:
      - VIRTUAL_HOST=examplesite.test
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - HTTPS_METHOD=redirect
    networks:
      - laraharbor-network
      - internal
    restart: unless-stopped
  
  examplesite-dbadmin:
    image: phpmyadmin/phpmyadmin
    container_name: examplesite-dbadmin
    depends_on:
      - examplesite-db
    environment:
      - PMA_HOST=examplesite-db
      - PMA_USER=root
      - PMA_PASSWORD=McELGV0hCzfiyvl3
      - VIRTUAL_HOST=admin.examplesite.test
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - HTTPS_METHOD=redirect
      - UPLOAD_LIMIT=128M
    networks:
      - internal
      - laraharbor-network
    restart: unless-stopped 